-- Blocky database schema for a fresh Supabase PostgreSQL project.
-- Use this script instead of running the Flask migrations against the same fresh database.

create table if not exists public.items (
    id integer generated by default as identity primary key,
    name varchar(120) not null,
    description varchar(500) not null default '',
    created_at timestamp without time zone not null default now()
);

create table if not exists public.users (
    id integer generated by default as identity primary key,
    name varchar(120) not null,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    created_at timestamp without time zone not null default now(),
    points integer not null default 0,
    theme varchar(30) not null default 'paper',
    profile_picture bytea,
    profile_picture_type varchar(50)
);

create table if not exists public.auth_sessions (
    id integer generated by default as identity primary key,
    session_id varchar(128) not null unique,
    user_id integer not null references public.users(id) on delete cascade,
    created_at timestamp without time zone not null default now(),
    last_seen_at timestamp without time zone not null default now(),
    expires_at timestamp without time zone not null,
    revoked_at timestamp without time zone,
    ip_address varchar(45),
    user_agent varchar(500)
);

create table if not exists public.login_attempts (
    id integer generated by default as identity primary key,
    email varchar(255) not null,
    ip_address varchar(45) not null,
    attempted_at timestamp without time zone not null default now()
);

create table if not exists public.lesson_progress (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    lesson_id varchar(80) not null,
    completed_at timestamp without time zone not null default now(),
    constraint uq_lesson_progress_user_lesson unique (user_id, lesson_id)
);

create index if not exists ix_users_email on public.users (email);
create index if not exists ix_auth_sessions_session_id on public.auth_sessions (session_id);
create index if not exists ix_auth_sessions_user_id on public.auth_sessions (user_id);
create index if not exists ix_login_attempts_email on public.login_attempts (email);
create index if not exists ix_login_attempts_ip_address on public.login_attempts (ip_address);
create index if not exists ix_login_attempts_attempted_at on public.login_attempts (attempted_at);
create index if not exists ix_lesson_progress_user_id on public.lesson_progress (user_id);
